---
# ============================================================
# Role: vmware — vars/main.yaml
# ============================================================

# --- vCenter ---
vcenter_hostname: "vcsa01-homelab.lcs.local"
vcenter_validate_certs: false
