---
# ============================================================
# Ansible Collections — poc-claro-hashicorp
# Instalar com: ansible-galaxy collection install -r requirements.yaml
# ============================================================
collections:
  - name: community.vmware
    version: ">=4.0.0"

  - name: community.hashi_vault
    version: ">=6.0.0"

  - name: ansible.utils
    version: ">=2.12.0"
