---
# ============================================================
# Role: hashicorp/consul — vars/main.yaml
# ============================================================

consul_version: "1.19.0"
consul_install_dir: "/opt/consul"
consul_config_dir: "/etc/consul.d"
consul_data_dir: "/opt/consul/data"

consul_client_addr: "0.0.0.0"
consul_http_port: 8500
consul_dns_port: 8600
consul_serf_lan_port: 8301
consul_serf_wan_port: 8302
consul_server_rpc_port: 8300

consul_bootstrap_expect: 3
consul_server_mode: true
consul_ui: true
